### ISSUE TITLE
[BUG] 登陆失败

### ISSUE THREAD

**Issue by aberter0x3f** [Icalingua-plus-plus/Icalingua-plus-plus#247]
无法登陆 QQ 账号，更换多种 Protocol 和 Status 或尝试扫码登陆均失败。

```yaml
{
  self_id: **********,
  time: 1660694122,
  post_type: 'system',
  system_type: 'login',
  sub_type: 'error',
  code: 235,
  message: '[温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面'
}
```
